# FROM node:latest
FROM node:20-bookworm-slim

ARG PORT=3500
ARG FRONTEND_URL
ARG BACKEND_URL
ARG APP_SECRET
ARG ORACLE_USER
ARG ORACLE_PASSWORD
ARG ORACLE_CONNECTION_STRING

ENV PORT=3500\
    FRONTEND_URL=${FRONTEND_URL}\
    BACKEND_URL=${BACKEND_URL}\
    APP_SECRET=${APP_SECRET}\
    ORACLE_USER=${ORACLE_USER}\
    ORACLE_PASSWORD=${ORACLE_PASSWORD}\
    ORACLE_CONNECTION_STRING=${ORACLE_CONNECTION_STRING}

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE $PORT

CMD [ "npm","run","start:prod" ]



