import { oracleDb } from "../database/connection";
import { uploadSupportAttachmentToS3 } from "./ociUpload.service";
import { emitSupportPresenceChanged, emitSupportTicketChanged, getConnectedSupportUsers, resolveSupportRole } from "./supportRealtime.service";

const ROOT_SCHEMA = "CUSTOMERS";

type UserContext = {
  loginid?: string;
  username?: string;
  company_code?: string;
  tenantId?: string;
};

type AttachmentInput = {
  file_name?: string;
  file_type?: string;
  file_size?: number;
  data_url?: string;
};

let initialized = false;

export class SupportChatService {
  static async ensureSchema() {
    if (initialized) return;
    await createTableIfMissing(
      "SUPPORT_TICKET",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_TICKET (
        TICKET_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        COMPANY_CODE VARCHAR2(20),
        TENANT_ID VARCHAR2(50),
        REQUESTER_LOGINID VARCHAR2(100) NOT NULL,
        REQUESTER_NAME VARCHAR2(400),
        ASSIGNED_TO VARCHAR2(100),
        SUBJECT VARCHAR2(300),
        MODULE_NAME VARCHAR2(100),
        PAGE_URL VARCHAR2(500),
        STATUS VARCHAR2(20) DEFAULT 'OPEN',
        PRIORITY VARCHAR2(20) DEFAULT 'NORMAL',
        LAST_MESSAGE CLOB,
        LAST_MESSAGE_AT DATE DEFAULT SYSDATE,
        CREATED_AT DATE DEFAULT SYSDATE,
        UPDATED_AT DATE DEFAULT SYSDATE,
        CLOSED_AT DATE
      )`
    );
    await createTableIfMissing(
      "SUPPORT_MESSAGE",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_MESSAGE (
        MESSAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TICKET_ID NUMBER NOT NULL,
        SENDER_LOGINID VARCHAR2(100) NOT NULL,
        SENDER_NAME VARCHAR2(400),
        SENDER_ROLE VARCHAR2(20),
        MESSAGE_TEXT CLOB,
        HAS_ATTACHMENTS CHAR(1) DEFAULT 'N',
        READ_AT DATE,
        IS_DELETED CHAR(1) DEFAULT 'N',
        DELETED_BY VARCHAR2(100),
        DELETED_AT DATE,
        CREATED_AT DATE DEFAULT SYSDATE
      )`
    );
    await addColumnIfMissing("SUPPORT_MESSAGE", "IS_DELETED", "CHAR(1) DEFAULT 'N'");
    await addColumnIfMissing("SUPPORT_MESSAGE", "DELETED_BY", "VARCHAR2(100)");
    await addColumnIfMissing("SUPPORT_MESSAGE", "DELETED_AT", "DATE");
    await createTableIfMissing(
      "SUPPORT_ATTACHMENT",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_ATTACHMENT (
        ATTACHMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TICKET_ID NUMBER NOT NULL,
        MESSAGE_ID NUMBER NOT NULL,
        FILE_NAME VARCHAR2(300),
        FILE_TYPE VARCHAR2(120),
        FILE_SIZE NUMBER,
        OBJECT_KEY VARCHAR2(1000),
        FILE_URL VARCHAR2(2000),
        DATA_URL CLOB,
        CREATED_AT DATE DEFAULT SYSDATE
      )`
    );
    await addColumnIfMissing("SUPPORT_ATTACHMENT", "OBJECT_KEY", "VARCHAR2(1000)");
    await addColumnIfMissing("SUPPORT_ATTACHMENT", "FILE_URL", "VARCHAR2(2000)");
    await createTableIfMissing(
      "SUPPORT_PRESENCE",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_PRESENCE (
        LOGINID VARCHAR2(100) PRIMARY KEY,
        USERNAME VARCHAR2(400),
        COMPANY_CODE VARCHAR2(20),
        TENANT_ID VARCHAR2(50),
        LAST_SEEN_AT VARCHAR2(30)
      )`
    );
    initialized = true;
  }

  static async heartbeat(user: UserContext) {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const nowSql = await presenceNowSql();
    const binds = {
      loginid,
      username: getUserName(user),
      companyCode: user.company_code || "",
      tenantId: user.tenantId || "",
    };
    const existing = await fetchOne(`SELECT LOGINID FROM ${ROOT_SCHEMA}.SUPPORT_PRESENCE WHERE LOGINID = :loginid`, { loginid });
    if (existing) {
      await oracleDb.query(
        `UPDATE ${ROOT_SCHEMA}.SUPPORT_PRESENCE
            SET USERNAME = :username,
                COMPANY_CODE = :companyCode,
                TENANT_ID = :tenantId,
                LAST_SEEN_AT = ${nowSql}
          WHERE LOGINID = :loginid`,
        binds
      );
    } else {
      await oracleDb.query(
        `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_PRESENCE
          (LOGINID, USERNAME, COMPANY_CODE, TENANT_ID, LAST_SEEN_AT)
         VALUES (:loginid, :username, :companyCode, :tenantId, ${nowSql})`,
        binds
      );
    }
    emitSupportPresenceChanged();
    return { loginid, online: true };
  }

  static async getActiveUsers() {
    await this.ensureSchema();
    const seen = lastSeenSql();
    const result = await oracleDb.query(
      `SELECT LOGINID, USERNAME, COMPANY_CODE, TENANT_ID,
              TO_CHAR(${seen}, 'YYYY-MM-DD HH24:MI:SS') AS LAST_SEEN_AT,
              CASE WHEN ${seen} >= SYSDATE - (5 / 1440) THEN 'Y' ELSE 'N' END AS IS_ONLINE
         FROM ${ROOT_SCHEMA}.SUPPORT_PRESENCE
        ORDER BY CASE WHEN ${seen} >= SYSDATE - (5 / 1440) THEN 0 ELSE 1 END,
                 ${seen} DESC`
    );
    return mergeConnectedUsers(await normalizeRows(result.rows || []));
  }

  static async getTickets(user: UserContext, requestedRole = "user") {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const role = resolveSupportRole(user, requestedRole);
    const isAdmin = role === "admin";
    const binds: Record<string, any> = { viewerLoginid: loginid };
    const where = isAdmin ? "" : "WHERE T.REQUESTER_LOGINID = :loginid OR T.ASSIGNED_TO = :loginid";
    if (!isAdmin) binds.loginid = loginid;
    const seen = lastSeenSql("P");
    const result = await oracleDb.query(
      `SELECT T.TICKET_ID, T.COMPANY_CODE, T.TENANT_ID, T.REQUESTER_LOGINID, T.REQUESTER_NAME,
              T.ASSIGNED_TO, T.SUBJECT, T.MODULE_NAME, T.PAGE_URL, T.STATUS, T.PRIORITY,
              DBMS_LOB.SUBSTR(T.LAST_MESSAGE, 4000, 1) AS LAST_MESSAGE,
              TO_CHAR(T.LAST_MESSAGE_AT, 'YYYY-MM-DD HH24:MI:SS') AS LAST_MESSAGE_AT,
              TO_CHAR(T.CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT,
              TO_CHAR(${seen}, 'YYYY-MM-DD HH24:MI:SS') AS REQUESTER_LAST_SEEN_AT,
              CASE WHEN ${seen} >= SYSDATE - (5 / 1440) THEN 'Y' ELSE 'N' END AS REQUESTER_IS_ONLINE,
              (SELECT COUNT(*) FROM ${ROOT_SCHEMA}.SUPPORT_MESSAGE M
                WHERE M.TICKET_ID = T.TICKET_ID
                  AND M.SENDER_LOGINID <> :viewerLoginid
                  AND NVL(M.IS_DELETED, 'N') <> 'Y'
                  AND M.READ_AT IS NULL) AS UNREAD_COUNT
         FROM ${ROOT_SCHEMA}.SUPPORT_TICKET T
         LEFT JOIN ${ROOT_SCHEMA}.SUPPORT_PRESENCE P ON P.LOGINID = T.REQUESTER_LOGINID
         ${where}
        ORDER BY T.LAST_MESSAGE_AT DESC`,
      binds
    );
    return normalizeRows(result.rows || []);
  }

  static async getMessages(ticketId: number, user: UserContext, requestedRole = "user") {
    await this.ensureSchema();
    await this.assertTicketAccess(ticketId, user, requestedRole);
    const connection = await oracleDb.getConnection();
    try {
      const messages = await oracleDb.query(
        `SELECT MESSAGE_ID, TICKET_ID, SENDER_LOGINID, SENDER_NAME, SENDER_ROLE,
                MESSAGE_TEXT, HAS_ATTACHMENTS, NVL(IS_DELETED, 'N') AS IS_DELETED, DELETED_BY,
                TO_CHAR(DELETED_AT, 'YYYY-MM-DD HH24:MI:SS') AS DELETED_AT,
                TO_CHAR(READ_AT, 'YYYY-MM-DD HH24:MI:SS') AS READ_AT,
                TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
           FROM ${ROOT_SCHEMA}.SUPPORT_MESSAGE
          WHERE TICKET_ID = :ticketId
          ORDER BY MESSAGE_ID`,
        { ticketId },
        connection
      );
      const attachments = await oracleDb.query(
        `SELECT ATTACHMENT_ID, TICKET_ID, MESSAGE_ID, FILE_NAME, FILE_TYPE, FILE_SIZE,
                DATA_URL, FILE_URL, OBJECT_KEY,
                TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
           FROM ${ROOT_SCHEMA}.SUPPORT_ATTACHMENT
          WHERE TICKET_ID = :ticketId
          ORDER BY ATTACHMENT_ID`,
        { ticketId },
        connection
      );
      const messageRows = await normalizeRows(messages.rows || []);
      const attachmentRows = await normalizeRows(attachments.rows || []);
      const byMessage = new Map<number, any[]>();
      for (const item of attachmentRows) {
        const key = Number(item.MESSAGE_ID);
        byMessage.set(key, [...(byMessage.get(key) || []), item]);
      }
      return messageRows.map((message: any) => {
        const deleted = message.IS_DELETED === "Y";
        return {
          ...message,
          MESSAGE_TEXT: deleted ? "This message was deleted" : message.MESSAGE_TEXT,
          attachments: deleted ? [] : byMessage.get(Number(message.MESSAGE_ID)) || [],
        };
      });
    } finally {
      await connection.close();
    }
  }

  static async createTicket(input: any, user: UserContext) {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const message = cleanText(input.message);
    const subject = cleanText(input.subject) || message.slice(0, 80) || "Support request";
    const result = await oracleDb.query(
      `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_TICKET
        (COMPANY_CODE, TENANT_ID, REQUESTER_LOGINID, REQUESTER_NAME, ASSIGNED_TO,
         SUBJECT, MODULE_NAME, PAGE_URL, STATUS, PRIORITY, LAST_MESSAGE, LAST_MESSAGE_AT,
         CREATED_AT, UPDATED_AT)
       VALUES
        (:companyCode, :tenantId, :loginid, :requesterName, :assignedTo,
         :subject, :moduleName, :pageUrl, 'OPEN', :priority, :message, SYSDATE,
         SYSDATE, SYSDATE)
       RETURNING TICKET_ID INTO :ticketId`,
      {
        companyCode: user.company_code || "",
        tenantId: user.tenantId || "",
        loginid,
        requesterName: getUserName(user),
        assignedTo: cleanText(input.assigned_to),
        subject,
        moduleName: cleanText(input.module),
        pageUrl: cleanText(input.page_url),
        priority: cleanText(input.priority) || "NORMAL",
        message,
        ticketId: { dir: (require("oracledb") as any).BIND_OUT, type: (require("oracledb") as any).NUMBER },
      }
    );
    const ticketId = Number(result.outBinds?.ticketId?.[0] || result.outBinds?.ticketId);
    const messageId = await this.insertMessage(ticketId, message, input.attachments || [], user, "USER");
    emitSupportTicketChanged({ requesterLoginid: loginid, assignedTo: cleanText(input.assigned_to), ticketId, actorLoginid: loginid });
    return { ticketId, messageId };
  }

  static async addMessage(ticketId: number, input: any, user: UserContext, requestedRole = "user") {
    await this.ensureSchema();
    const ticket = await this.assertTicketAccess(ticketId, user, requestedRole);
    const role = resolveSupportRole(user, requestedRole);
    const message = cleanText(input.message);
    const messageId = await this.insertMessage(ticketId, message, input.attachments || [], user, role === "admin" ? "ADMIN" : "USER");
    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_TICKET
          SET LAST_MESSAGE = :message,
              LAST_MESSAGE_AT = SYSDATE,
              UPDATED_AT = SYSDATE,
              STATUS = CASE WHEN STATUS = 'CLOSED' THEN 'OPEN' ELSE STATUS END
        WHERE TICKET_ID = :ticketId`,
      { message, ticketId }
    );
    if (String(ticket.STATUS || "").toUpperCase() === "CLOSED" && role !== "admin") {
      await this.insertSystemMessage(ticketId, "Ticket reopened by customer reply.");
    }
    emitSupportTicketChanged({ requesterLoginid: ticket.REQUESTER_LOGINID, assignedTo: ticket.ASSIGNED_TO, ticketId, actorLoginid: getLoginId(user) });
    return { ticketId, messageId };
  }

  static async updateTicket(ticketId: number, input: any, user: UserContext, requestedRole = "user") {
    await this.ensureSchema();
    const ticket = await this.assertTicketAccess(ticketId, user, requestedRole);
    const role = resolveSupportRole(user, requestedRole);
    const status = cleanText(input.status).toUpperCase();
    const assignedTo = cleanText(input.assigned_to);
    const priority = cleanText(input.priority).toUpperCase();
    const previousStatus = String(ticket.STATUS || "").toUpperCase();
    if (status === "CLOSED" && role !== "admin") {
      throw new Error("Only support admins can close tickets");
    }
    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_TICKET
          SET STATUS = CASE WHEN :statusValue IS NULL THEN STATUS ELSE :statusValue END,
              ASSIGNED_TO = CASE WHEN :assignedTo IS NULL THEN ASSIGNED_TO ELSE :assignedTo END,
              PRIORITY = CASE WHEN :priority IS NULL THEN PRIORITY ELSE :priority END,
              UPDATED_AT = SYSDATE,
              CLOSED_AT = CASE WHEN :statusValue = 'CLOSED' THEN SYSDATE ELSE CLOSED_AT END
        WHERE TICKET_ID = :ticketId`,
      { ticketId, statusValue: status || null, assignedTo: assignedTo || null, priority: priority || null }
    );
    if (status === "CLOSED" && previousStatus !== "CLOSED") {
      const closeMessage = "Your ticket has been closed by support. If the issue is not solved, please reply here and the ticket will reopen.";
      await this.insertSystemMessage(ticketId, closeMessage);
      await oracleDb.query(
        `UPDATE ${ROOT_SCHEMA}.SUPPORT_TICKET
            SET LAST_MESSAGE = :message,
                LAST_MESSAGE_AT = SYSDATE,
                UPDATED_AT = SYSDATE
          WHERE TICKET_ID = :ticketId`,
        { ticketId, message: closeMessage }
      );
    }
    emitSupportTicketChanged({ requesterLoginid: ticket.REQUESTER_LOGINID, assignedTo: assignedTo || ticket.ASSIGNED_TO, ticketId, actorLoginid: getLoginId(user) });
    return { ticketId };
  }

  static async markRead(ticketId: number, user: UserContext) {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const result = await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_MESSAGE
          SET READ_AT = SYSDATE
        WHERE TICKET_ID = :ticketId
          AND SENDER_LOGINID <> :loginid
          AND READ_AT IS NULL`,
      { ticketId, loginid }
    );
    if (!Number(result?.rowsAffected || 0)) {
      return { ticketId, changed: false };
    }
    const ticket = await fetchOne(
      `SELECT REQUESTER_LOGINID, ASSIGNED_TO FROM ${ROOT_SCHEMA}.SUPPORT_TICKET WHERE TICKET_ID = :ticketId`,
      { ticketId }
    );
    emitSupportTicketChanged({ requesterLoginid: ticket?.REQUESTER_LOGINID, assignedTo: ticket?.ASSIGNED_TO, ticketId, actorLoginid: loginid });
    return { ticketId, changed: true };
  }

  static async deleteMessage(ticketId: number, messageId: number, user: UserContext, requestedRole = "user") {
    await this.ensureSchema();
    const ticket = await this.assertTicketAccess(ticketId, user, requestedRole);
    const loginid = getLoginId(user);
    const message = await fetchOne(
      `SELECT MESSAGE_ID, TICKET_ID, SENDER_LOGINID, NVL(IS_DELETED, 'N') AS IS_DELETED
         FROM ${ROOT_SCHEMA}.SUPPORT_MESSAGE
        WHERE TICKET_ID = :ticketId
          AND MESSAGE_ID = :messageId`,
      { ticketId, messageId }
    );
    if (!message) throw new Error("Support message not found");
    if (message.IS_DELETED === "Y") return { ticketId, messageId, deleted: true };
    if (String(message.SENDER_LOGINID || "").toUpperCase() !== loginid.toUpperCase()) {
      throw new Error("You can delete only your own support messages");
    }

    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_MESSAGE
          SET MESSAGE_TEXT = 'This message was deleted',
              HAS_ATTACHMENTS = 'N',
              IS_DELETED = 'Y',
              DELETED_BY = :loginid,
              DELETED_AT = SYSDATE
        WHERE TICKET_ID = :ticketId
          AND MESSAGE_ID = :messageId`,
      { ticketId, messageId, loginid }
    );
    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_TICKET T
          SET LAST_MESSAGE = NVL((
                SELECT DBMS_LOB.SUBSTR(M.MESSAGE_TEXT, 4000, 1)
                  FROM ${ROOT_SCHEMA}.SUPPORT_MESSAGE M
                 WHERE M.TICKET_ID = :ticketId
                   AND NVL(M.IS_DELETED, 'N') <> 'Y'
                 ORDER BY M.MESSAGE_ID DESC
                 FETCH FIRST 1 ROW ONLY
              ), 'Message deleted'),
              LAST_MESSAGE_AT = SYSDATE,
              UPDATED_AT = SYSDATE
        WHERE T.TICKET_ID = :ticketId`,
      { ticketId }
    );
    emitSupportTicketChanged({ requesterLoginid: ticket.REQUESTER_LOGINID, assignedTo: ticket.ASSIGNED_TO, ticketId, actorLoginid: loginid });
    return { ticketId, messageId, deleted: true };
  }

  private static async assertTicketAccess(ticketId: number, user: UserContext, requestedRole = "user") {
    const loginid = getLoginId(user);
    const role = resolveSupportRole(user, requestedRole);
    const row = await fetchOne(
      `SELECT TICKET_ID, REQUESTER_LOGINID, ASSIGNED_TO
              , STATUS
         FROM ${ROOT_SCHEMA}.SUPPORT_TICKET
        WHERE TICKET_ID = :ticketId
          ${role === "admin" ? "" : "AND (REQUESTER_LOGINID = :loginid OR ASSIGNED_TO = :loginid)"}`,
      role === "admin" ? { ticketId } : { ticketId, loginid }
    );
    if (!row) throw new Error("Support ticket not found or not accessible");
    return row;
  }

  private static async insertSystemMessage(ticketId: number, message: string) {
    await oracleDb.query(
      `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_MESSAGE
        (TICKET_ID, SENDER_LOGINID, SENDER_NAME, SENDER_ROLE, MESSAGE_TEXT, HAS_ATTACHMENTS, CREATED_AT)
       VALUES (:ticketId, 'SUPPORT_SYSTEM', 'Support', 'SYSTEM', :message, 'N', SYSDATE)`,
      { ticketId, message }
    );
  }

  private static async insertMessage(ticketId: number, message: string, attachments: AttachmentInput[], user: UserContext, senderRole: string) {
    const result = await oracleDb.query(
      `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_MESSAGE
        (TICKET_ID, SENDER_LOGINID, SENDER_NAME, SENDER_ROLE, MESSAGE_TEXT, HAS_ATTACHMENTS, CREATED_AT)
       VALUES (:ticketId, :loginid, :senderName, :senderRole, :message, :hasAttachments, SYSDATE)
       RETURNING MESSAGE_ID INTO :messageId`,
      {
        ticketId,
        loginid: getLoginId(user),
        senderName: getUserName(user),
        senderRole,
        message,
        hasAttachments: attachments.length ? "Y" : "N",
        messageId: { dir: (require("oracledb") as any).BIND_OUT, type: (require("oracledb") as any).NUMBER },
      }
    );
    const messageId = Number(result.outBinds?.messageId?.[0] || result.outBinds?.messageId);
    for (const attachment of attachments.slice(0, 5)) {
      const stored = await storeAttachmentInObjectStorage(attachment, ticketId, messageId, user);
      await oracleDb.query(
        `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_ATTACHMENT
          (TICKET_ID, MESSAGE_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, OBJECT_KEY, FILE_URL, DATA_URL, CREATED_AT)
         VALUES (:ticketId, :messageId, :fileName, :fileType, :fileSize, :objectKey, :fileUrl, :dataUrl, SYSDATE)`,
        {
          ticketId,
          messageId,
          fileName: stored.fileName,
          fileType: stored.fileType,
          fileSize: stored.fileSize,
          objectKey: stored.objectKey,
          fileUrl: stored.fileUrl,
          dataUrl: stored.dataUrlFallback,
        }
      );
    }
    return messageId;
  }
}

async function createTableIfMissing(tableName: string, ddl: string) {
  const exists = await fetchOne(
    `SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = :owner AND TABLE_NAME = :tableName`,
    { owner: ROOT_SCHEMA, tableName }
  );
  if (exists) return;
  await oracleDb.query(ddl);
}

async function storeAttachmentInObjectStorage(attachment: AttachmentInput, ticketId: number, messageId: number, user: UserContext) {
  const fileName = cleanFileName(attachment.file_name || `attachment-${Date.now()}.bin`).slice(0, 300);
  const fileType = cleanText(attachment.file_type).slice(0, 120) || "application/octet-stream";
  const parsed = parseDataUrl(cleanText(attachment.data_url), fileType);
  if (!parsed) {
    return {
      fileName,
      fileType,
      fileSize: Number(attachment.file_size) || 0,
      objectKey: null,
      fileUrl: cleanText(attachment.data_url) || null,
      dataUrlFallback: null,
    };
  }

  const safeTenant = safeObjectSegment(user.tenantId || user.company_code || "tenant");
  const safeLogin = safeObjectSegment(getLoginId(user));
  const objectKey = [
    "support-chat",
    safeTenant,
    String(ticketId),
    String(messageId),
    `${Date.now()}-${safeLogin}-${fileName}`,
  ].join("/");
  const fileUrl = await uploadSupportAttachmentToS3(parsed.buffer, objectKey, parsed.contentType);

  return {
    fileName,
    fileType: parsed.contentType,
    fileSize: parsed.buffer.length,
    objectKey,
    fileUrl,
    dataUrlFallback: null,
  };
}

function parseDataUrl(dataUrl: string, fallbackType: string) {
  const match = dataUrl.match(/^data:([^;,]+)?(?:;[^,]*)?;base64,(.*)$/);
  if (!match) return null;
  return {
    contentType: match[1] || fallbackType || "application/octet-stream",
    buffer: Buffer.from(match[2], "base64"),
  };
}

function cleanFileName(value: string) {
  const cleaned = cleanText(value).replace(/[\\/:*?"<>|]+/g, "-").replace(/\s+/g, " ").trim();
  return cleaned || `attachment-${Date.now()}.bin`;
}

function safeObjectSegment(value: string) {
  return cleanText(value).replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || "unknown";
}

function mergeConnectedUsers(rows: any[]) {
  const byLogin = new Map<string, any>();
  for (const row of rows) {
    byLogin.set(String(row.LOGINID || "").toUpperCase(), row);
  }
  for (const connected of getConnectedSupportUsers()) {
    const key = String(connected.LOGINID || "").toUpperCase();
    byLogin.set(key, { ...(byLogin.get(key) || {}), ...connected, IS_ONLINE: "Y" });
  }
  return Array.from(byLogin.values()).sort((first, second) => {
    if (first.IS_ONLINE !== second.IS_ONLINE) return first.IS_ONLINE === "Y" ? -1 : 1;
    return String(first.USERNAME || first.LOGINID || "").localeCompare(String(second.USERNAME || second.LOGINID || ""));
  });
}

async function addColumnIfMissing(tableName: string, columnName: string, definition: string) {
  const exists = await fetchOne(
    `SELECT COLUMN_NAME
       FROM ALL_TAB_COLUMNS
      WHERE OWNER = :owner
        AND TABLE_NAME = :tableName
        AND COLUMN_NAME = :columnName`,
    { owner: ROOT_SCHEMA, tableName, columnName }
  );
  if (exists) return;
  await oracleDb.query(`ALTER TABLE ${ROOT_SCHEMA}.${tableName} ADD (${columnName} ${definition})`);
}

async function fetchOne(sql: string, binds: Record<string, any>) {
  const result = await oracleDb.query(sql, binds);
  return result.rows?.[0] || null;
}

function lastSeenSql(alias?: string) {
  const columnRef = `${alias ? `${alias}.` : ""}LAST_SEEN_AT`;
  const textExpr = `TRIM(TO_CHAR(${columnRef}))`;
  return `CASE
    WHEN ${columnRef} IS NULL THEN NULL
    WHEN REGEXP_LIKE(${textExpr}, '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$') THEN TO_DATE(${textExpr}, 'YYYY-MM-DD HH24:MI:SS')
    WHEN REGEXP_LIKE(${textExpr}, '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN TO_DATE(${textExpr}, 'YYYY-MM-DD')
    WHEN REGEXP_LIKE(${textExpr}, '^[0-9]{2}-[[:alpha:]]{3}-[0-9]{2}$') THEN TO_DATE(${textExpr}, 'DD-MON-RR', 'NLS_DATE_LANGUAGE=English')
    WHEN REGEXP_LIKE(${textExpr}, '^[0-9]{2}/[0-9]{2}/[0-9]{4}$') THEN TO_DATE(${textExpr}, 'DD/MM/YYYY')
    ELSE NULL
  END`;
}

async function presenceNowSql() {
  const dataType = await getColumnDataType("SUPPORT_PRESENCE", "LAST_SEEN_AT");
  if (dataType === "DATE" || dataType.startsWith("TIMESTAMP")) return "SYSDATE";
  return "TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')";
}

async function getColumnDataType(tableName: string, columnName: string) {
  const row = await fetchOne(
    `SELECT DATA_TYPE
       FROM ALL_TAB_COLUMNS
      WHERE OWNER = :owner
        AND TABLE_NAME = :tableName
        AND COLUMN_NAME = :columnName`,
    { owner: ROOT_SCHEMA, tableName, columnName }
  );
  return String(row?.DATA_TYPE || "").toUpperCase();
}

function getLoginId(user: UserContext) {
  return cleanText(user.loginid || (user as any).LOGINID || "UNKNOWN").toUpperCase();
}

function getUserName(user: UserContext) {
  return cleanText(user.username || (user as any).USERNAME || getLoginId(user));
}

function cleanText(value: unknown) {
  if (value === undefined || value === null) return "";
  return String(value);
}

async function normalizeRows(rows: any[]) {
  return await Promise.all(rows.map(normalizeRow));
}

async function normalizeRow(row: any) {
  const next: any = { ...row };
  for (const [key, value] of Object.entries(next)) {
    if (isLob(value)) next[key] = await lobToString(value);
  }
  return next;
}

function isLob(value: any) {
  return value && typeof value === "object" && typeof value.on === "function" && typeof value.setEncoding === "function";
}

function lobToString(lob: any): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = "";
    lob.setEncoding("utf8");
    lob.on("data", (chunk: string) => {
      data += chunk;
    });
    lob.on("end", () => resolve(data));
    lob.on("error", reject);
  });
}
