import { oracleDb } from "../database/connection";

const ROOT_SCHEMA = "CUSTOMERS";

type UserContext = {
  loginid?: string;
  username?: string;
  company_code?: string;
  tenantId?: string;
};

type TicketInput = {
  subject?: string;
  message?: string;
  module?: string;
  page_url?: string;
  priority?: string;
  assigned_to?: string;
  attachments?: AttachmentInput[];
};

type MessageInput = {
  message?: string;
  attachments?: AttachmentInput[];
};

type AttachmentInput = {
  file_name?: string;
  file_type?: string;
  file_size?: number;
  data_url?: string;
};

let initialized = false;

export class SupportChatService {
  static async ensureSchema() {
    if (initialized) return;
    await createTableIfMissing(
      "SUPPORT_TICKET",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_TICKET (
        TICKET_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        COMPANY_CODE VARCHAR2(20),
        TENANT_ID VARCHAR2(50),
        REQUESTER_LOGINID VARCHAR2(100) NOT NULL,
        REQUESTER_NAME VARCHAR2(400),
        ASSIGNED_TO VARCHAR2(100),
        SUBJECT VARCHAR2(300),
        MODULE_NAME VARCHAR2(100),
        PAGE_URL VARCHAR2(500),
        STATUS VARCHAR2(20) DEFAULT 'OPEN',
        PRIORITY VARCHAR2(20) DEFAULT 'NORMAL',
        LAST_MESSAGE CLOB,
        LAST_MESSAGE_AT DATE DEFAULT SYSDATE,
        CREATED_AT DATE DEFAULT SYSDATE,
        UPDATED_AT DATE DEFAULT SYSDATE,
        CLOSED_AT DATE
      )`
    );
    await createTableIfMissing(
      "SUPPORT_MESSAGE",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_MESSAGE (
        MESSAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TICKET_ID NUMBER NOT NULL,
        SENDER_LOGINID VARCHAR2(100) NOT NULL,
        SENDER_NAME VARCHAR2(400),
        SENDER_ROLE VARCHAR2(20),
        MESSAGE_TEXT CLOB,
        HAS_ATTACHMENTS CHAR(1) DEFAULT 'N',
        READ_AT DATE,
        CREATED_AT DATE DEFAULT SYSDATE
      )`
    );
    await createTableIfMissing(
      "SUPPORT_ATTACHMENT",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_ATTACHMENT (
        ATTACHMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TICKET_ID NUMBER NOT NULL,
        MESSAGE_ID NUMBER NOT NULL,
        FILE_NAME VARCHAR2(300),
        FILE_TYPE VARCHAR2(120),
        FILE_SIZE NUMBER,
        DATA_URL CLOB,
        CREATED_AT DATE DEFAULT SYSDATE
      )`
    );
    await createTableIfMissing(
      "SUPPORT_PRESENCE",
      `CREATE TABLE ${ROOT_SCHEMA}.SUPPORT_PRESENCE (
        LOGINID VARCHAR2(100) PRIMARY KEY,
        USERNAME VARCHAR2(400),
        COMPANY_CODE VARCHAR2(20),
        TENANT_ID VARCHAR2(50),
        LAST_SEEN_AT DATE DEFAULT SYSDATE
      )`
    );
    initialized = true;
  }

  static async heartbeat(user: UserContext) {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const existing = await fetchOne(
      `SELECT LOGINID FROM ${ROOT_SCHEMA}.SUPPORT_PRESENCE WHERE LOGINID = :loginid`,
      { loginid }
    );
    const binds = {
      loginid,
      username: getUserName(user),
      companyCode: user.company_code || "",
      tenantId: user.tenantId || "",
    };
    if (existing) {
      await oracleDb.query(
        `UPDATE ${ROOT_SCHEMA}.SUPPORT_PRESENCE
            SET USERNAME = :username,
                COMPANY_CODE = :companyCode,
                TENANT_ID = :tenantId,
                LAST_SEEN_AT = SYSDATE
          WHERE LOGINID = :loginid`,
        binds
      );
    } else {
      await oracleDb.query(
        `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_PRESENCE
          (LOGINID, USERNAME, COMPANY_CODE, TENANT_ID, LAST_SEEN_AT)
         VALUES (:loginid, :username, :companyCode, :tenantId, SYSDATE)`,
        binds
      );
    }
    return { loginid, online: true };
  }

  static async getActiveUsers() {
    await this.ensureSchema();
    const result = await oracleDb.query(
      `SELECT LOGINID, USERNAME, COMPANY_CODE, TENANT_ID,
              TO_CHAR(LAST_SEEN_AT, 'YYYY-MM-DD HH24:MI:SS') AS LAST_SEEN_AT,
              CASE WHEN LAST_SEEN_AT >= SYSDATE - (5 / 1440) THEN 'Y' ELSE 'N' END AS IS_ONLINE
         FROM ${ROOT_SCHEMA}.SUPPORT_PRESENCE
        ORDER BY CASE WHEN LAST_SEEN_AT >= SYSDATE - (5 / 1440) THEN 0 ELSE 1 END,
                 LAST_SEEN_AT DESC`
    );
    return await normalizeRows(result.rows || []);
  }

  static async getDirectory() {
    await this.ensureSchema();
    const result = await oracleDb.query(
      `SELECT U.LOGINID, U.USERNAME, U.EMAIL_ID, U.COMPANY_CODE,
              NVL(P.TENANT_ID, '') AS TENANT_ID,
              TO_CHAR(P.LAST_SEEN_AT, 'YYYY-MM-DD HH24:MI:SS') AS LAST_SEEN_AT,
              CASE WHEN P.LAST_SEEN_AT >= SYSDATE - (5 / 1440) THEN 'Y' ELSE 'N' END AS IS_ONLINE
         FROM ${ROOT_SCHEMA}.SEC_LOGINTEST U
         LEFT JOIN ${ROOT_SCHEMA}.SUPPORT_PRESENCE P ON P.LOGINID = U.LOGINID
        WHERE NVL(U.ACTIVE_FLAG, 'Y') = 'Y'
        ORDER BY CASE WHEN P.LAST_SEEN_AT >= SYSDATE - (5 / 1440) THEN 0 ELSE 1 END,
                 U.LOGINID`
    );
    return await normalizeRows(result.rows || []);
  }

  static async getTickets(user: UserContext, role = "user") {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const isAdmin = role.toLowerCase() === "admin";
    const binds: Record<string, any> = {};
    const where = isAdmin ? "" : "WHERE T.REQUESTER_LOGINID = :loginid OR T.ASSIGNED_TO = :loginid";
    if (!isAdmin) binds.loginid = loginid;
    const result = await oracleDb.query(
      `SELECT T.TICKET_ID, T.COMPANY_CODE, T.TENANT_ID, T.REQUESTER_LOGINID, T.REQUESTER_NAME,
              T.ASSIGNED_TO, T.SUBJECT, T.MODULE_NAME, T.PAGE_URL, T.STATUS, T.PRIORITY,
              T.LAST_MESSAGE, TO_CHAR(T.LAST_MESSAGE_AT, 'YYYY-MM-DD HH24:MI:SS') AS LAST_MESSAGE_AT,
              TO_CHAR(T.CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT,
              TO_CHAR(P.LAST_SEEN_AT, 'YYYY-MM-DD HH24:MI:SS') AS REQUESTER_LAST_SEEN_AT,
              CASE WHEN P.LAST_SEEN_AT >= SYSDATE - (5 / 1440) THEN 'Y' ELSE 'N' END AS REQUESTER_IS_ONLINE,
              (SELECT COUNT(*) FROM ${ROOT_SCHEMA}.SUPPORT_MESSAGE M
                WHERE M.TICKET_ID = T.TICKET_ID
                  AND M.SENDER_LOGINID <> :viewerLoginid
                  AND M.READ_AT IS NULL) AS UNREAD_COUNT
         FROM ${ROOT_SCHEMA}.SUPPORT_TICKET T
         LEFT JOIN ${ROOT_SCHEMA}.SUPPORT_PRESENCE P ON P.LOGINID = T.REQUESTER_LOGINID
         ${where}
        ORDER BY T.LAST_MESSAGE_AT DESC`,
      { ...binds, viewerLoginid: loginid }
    );
    return await normalizeRows(result.rows || []);
  }

  static async getMessages(ticketId: number, user: UserContext, role = "user") {
    await this.ensureSchema();
    await this.assertTicketAccess(ticketId, user, role);
    const messages = await oracleDb.query(
      `SELECT MESSAGE_ID, TICKET_ID, SENDER_LOGINID, SENDER_NAME, SENDER_ROLE,
              MESSAGE_TEXT, HAS_ATTACHMENTS, TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
         FROM ${ROOT_SCHEMA}.SUPPORT_MESSAGE
        WHERE TICKET_ID = :ticketId
        ORDER BY MESSAGE_ID`,
      { ticketId }
    );
    const attachments = await oracleDb.query(
      `SELECT ATTACHMENT_ID, TICKET_ID, MESSAGE_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, DATA_URL,
              TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
         FROM ${ROOT_SCHEMA}.SUPPORT_ATTACHMENT
        WHERE TICKET_ID = :ticketId
        ORDER BY ATTACHMENT_ID`,
      { ticketId }
    );
    const messageRows = await normalizeRows(messages.rows || []);
    const attachmentRows = await normalizeRows(attachments.rows || []);
    const byMessage = new Map<number, any[]>();
    for (const item of attachmentRows) {
      const key = Number(item.MESSAGE_ID);
      byMessage.set(key, [...(byMessage.get(key) || []), item]);
    }
    return messageRows.map((message: any) => ({
      ...message,
      attachments: byMessage.get(Number(message.MESSAGE_ID)) || [],
    }));
  }

  static async createTicket(input: TicketInput, user: UserContext) {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    const message = cleanText(input.message);
    const subject = cleanText(input.subject) || message.slice(0, 80) || "Support request";
    const ticketResult = await oracleDb.query(
      `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_TICKET
        (COMPANY_CODE, TENANT_ID, REQUESTER_LOGINID, REQUESTER_NAME, ASSIGNED_TO,
         SUBJECT, MODULE_NAME, PAGE_URL, STATUS, PRIORITY, LAST_MESSAGE, LAST_MESSAGE_AT,
         CREATED_AT, UPDATED_AT)
       VALUES
        (:companyCode, :tenantId, :loginid, :requesterName, :assignedTo,
         :subject, :moduleName, :pageUrl, 'OPEN', :priority, :message, SYSDATE,
         SYSDATE, SYSDATE)
       RETURNING TICKET_ID INTO :ticketId`,
      {
        companyCode: user.company_code || "",
        tenantId: user.tenantId || "",
        loginid,
        requesterName: getUserName(user),
        assignedTo: cleanText(input.assigned_to),
        subject,
        moduleName: cleanText(input.module),
        pageUrl: cleanText(input.page_url),
        priority: cleanText(input.priority) || "NORMAL",
        message,
        ticketId: { dir: (require("oracledb") as any).BIND_OUT, type: (require("oracledb") as any).NUMBER },
      }
    );
    const ticketId = Number(ticketResult.outBinds?.ticketId?.[0] || ticketResult.outBinds?.ticketId);
    const messageId = await this.insertMessage(ticketId, message, input.attachments || [], user, "USER");
    return { ticketId, messageId };
  }

  static async addMessage(ticketId: number, input: MessageInput, user: UserContext, role = "user") {
    await this.ensureSchema();
    await this.assertTicketAccess(ticketId, user, role);
    const message = cleanText(input.message);
    const messageId = await this.insertMessage(ticketId, message, input.attachments || [], user, role.toUpperCase() === "ADMIN" ? "ADMIN" : "USER");
    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_TICKET
          SET LAST_MESSAGE = :message,
              LAST_MESSAGE_AT = SYSDATE,
              UPDATED_AT = SYSDATE,
              STATUS = CASE WHEN STATUS = 'CLOSED' THEN 'OPEN' ELSE STATUS END
        WHERE TICKET_ID = :ticketId`,
      { message, ticketId }
    );
    return { ticketId, messageId };
  }

  static async updateTicket(ticketId: number, input: any, user: UserContext, role = "user") {
    await this.ensureSchema();
    await this.assertTicketAccess(ticketId, user, role);
    const status = cleanText(input.status).toUpperCase();
    const assignedTo = cleanText(input.assigned_to);
    const priority = cleanText(input.priority).toUpperCase();
    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_TICKET
          SET STATUS = CASE WHEN :statusValue IS NULL THEN STATUS ELSE :statusValue END,
              ASSIGNED_TO = CASE WHEN :assignedTo IS NULL THEN ASSIGNED_TO ELSE :assignedTo END,
              PRIORITY = CASE WHEN :priority IS NULL THEN PRIORITY ELSE :priority END,
              UPDATED_AT = SYSDATE,
              CLOSED_AT = CASE WHEN :statusValue = 'CLOSED' THEN SYSDATE ELSE CLOSED_AT END
        WHERE TICKET_ID = :ticketId`,
      {
        ticketId,
        statusValue: status || null,
        assignedTo: assignedTo || null,
        priority: priority || null,
      }
    );
    return { ticketId };
  }

  static async markRead(ticketId: number, user: UserContext) {
    await this.ensureSchema();
    const loginid = getLoginId(user);
    await oracleDb.query(
      `UPDATE ${ROOT_SCHEMA}.SUPPORT_MESSAGE
          SET READ_AT = SYSDATE
        WHERE TICKET_ID = :ticketId
          AND SENDER_LOGINID <> :loginid
          AND READ_AT IS NULL`,
      { ticketId, loginid }
    );
    return { ticketId };
  }

  private static async insertMessage(ticketId: number, message: string, attachments: AttachmentInput[], user: UserContext, senderRole: string) {
    const result = await oracleDb.query(
      `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_MESSAGE
        (TICKET_ID, SENDER_LOGINID, SENDER_NAME, SENDER_ROLE, MESSAGE_TEXT, HAS_ATTACHMENTS, CREATED_AT)
       VALUES (:ticketId, :loginid, :senderName, :senderRole, :message, :hasAttachments, SYSDATE)
       RETURNING MESSAGE_ID INTO :messageId`,
      {
        ticketId,
        loginid: getLoginId(user),
        senderName: getUserName(user),
        senderRole,
        message,
        hasAttachments: attachments.length ? "Y" : "N",
        messageId: { dir: (require("oracledb") as any).BIND_OUT, type: (require("oracledb") as any).NUMBER },
      }
    );
    const messageId = Number(result.outBinds?.messageId?.[0] || result.outBinds?.messageId);
    for (const attachment of attachments.slice(0, 5)) {
      await oracleDb.query(
        `INSERT INTO ${ROOT_SCHEMA}.SUPPORT_ATTACHMENT
          (TICKET_ID, MESSAGE_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, DATA_URL, CREATED_AT)
         VALUES (:ticketId, :messageId, :fileName, :fileType, :fileSize, :dataUrl, SYSDATE)`,
        {
          ticketId,
          messageId,
          fileName: cleanText(attachment.file_name).slice(0, 300),
          fileType: cleanText(attachment.file_type).slice(0, 120),
          fileSize: Number(attachment.file_size) || 0,
          dataUrl: cleanText(attachment.data_url),
        }
      );
    }
    return messageId;
  }

  private static async assertTicketAccess(ticketId: number, user: UserContext, role = "user") {
    const isAdmin = role.toLowerCase() === "admin";
    if (isAdmin) return;
    const row = await fetchOne(
      `SELECT TICKET_ID FROM ${ROOT_SCHEMA}.SUPPORT_TICKET
        WHERE TICKET_ID = :ticketId
          AND (REQUESTER_LOGINID = :loginid OR ASSIGNED_TO = :loginid)`,
      { ticketId, loginid: getLoginId(user) }
    );
    if (!row) throw new Error("Support ticket not found or not accessible");
  }
}

async function createTableIfMissing(tableName: string, ddl: string) {
  try {
    await oracleDb.query(ddl);
  } catch (error: any) {
    if (error?.errorNum === 955 || String(error?.message || "").includes("ORA-00955")) return;
    throw error;
  }
}

async function fetchOne(sql: string, binds: Record<string, any>) {
  const result = await oracleDb.query(sql, binds);
  return result.rows?.[0] || null;
}

function getLoginId(user: UserContext) {
  return cleanText(user.loginid || (user as any).LOGINID || "UNKNOWN");
}

function getUserName(user: UserContext) {
  return cleanText(user.username || (user as any).USERNAME || getLoginId(user));
}

function cleanText(value: unknown) {
  if (value === undefined || value === null) return "";
  return String(value);
}

async function normalizeRows(rows: any[]) {
  return await Promise.all(rows.map(normalizeRow));
}

async function normalizeRow(row: any) {
  const next: any = { ...row };
  for (const [key, value] of Object.entries(next)) {
    if (isLob(value)) {
      next[key] = await lobToString(value);
    }
  }
  return next;
}

function isLob(value: any) {
  return value && typeof value === "object" && typeof value.on === "function" && typeof value.setEncoding === "function";
}

function lobToString(lob: any): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = "";
    lob.setEncoding("utf8");
    lob.on("data", (chunk: string) => {
      data += chunk;
    });
    lob.on("end", () => resolve(data));
    lob.on("error", reject);
  });
}
