-- =============================================================================
-- SCRIPT: 01_CREATE_FREIGHT_TRACKER_SCHEMA.sql
-- PURPOSE: Dynamic Multi-Company Shipment Tracker Tables, Indexes, and MS_APPROVER_LEVELS Seeds
-- SCHEMA: WMSTST
-- =============================================================================

SET DEFINE OFF;

-- -----------------------------------------------------------------------------
-- 1. SHIPMENT TRACKING HEADER
-- Extends TI_JOB with operational stages, DO validity, and tracking flags
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WMSTST.TRK_SHIPMENT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE WMSTST.TRK_SHIPMENT (
    COMPANY_CODE            VARCHAR2(5)   NOT NULL,
    PRIN_CODE               VARCHAR2(5)   NOT NULL,
    JOB_NO                  VARCHAR2(15)  NOT NULL,
    BL_NUMBER               VARCHAR2(100),
    INVOICE_NUMBER          VARCHAR2(100),
    SHIPMENT_TYPE           VARCHAR2(20)  DEFAULT 'IMPORT' NOT NULL, -- IMPORT, EXPORT, LAND_IMPORT, AIR_IMPORT
    CURRENT_STAGE           VARCHAR2(30)  DEFAULT 'CUSTOMER' NOT NULL, -- CUSTOMER, FFD_REVIEW, IN_PROGRESS, TRANSPORT, DC_TRANSPORT, COMPLETED
    PULL_OUT_DATE           DATE,
    DO_VALIDITY_DATE        DATE,
    PERMIT_REF              VARCHAR2(200),
    PERMIT_NOT_REQUIRED     CHAR(1)       DEFAULT 'N' NOT NULL,
    IS_DRY                  CHAR(1)       DEFAULT 'N' NOT NULL,
    IS_IMPORTANT            CHAR(1)       DEFAULT 'N' NOT NULL,
    CUSTOMS_RELEASE_STATUS  VARCHAR2(20)  DEFAULT 'NONE' NOT NULL, -- NONE, PENDING, CLEARED
    ETA_AT_PORT             DATE,
    PRODUCT_TYPE_ID         VARCHAR2(50),
    SHIPPING_LINE_ID        VARCHAR2(50),
    OFFLOADING_POINT_ID     VARCHAR2(50),
    EMPTY_RETURN_POINT_ID   VARCHAR2(50),
    AIRPORT_ID              VARCHAR2(50),
    BAYAN_TYPE_ID           VARCHAR2(50),
    EXPORT_BAYAN_NO         VARCHAR2(100),
    TRUCK_NUMBERS           VARCHAR2(500),
    DATE_OF_LOADING         DATE,
    LOADED_AT               DATE,
    EXPORT_DOCS_COMPLETED_AT DATE,
    COMPLETED_AT            DATE,
    CREATED_BY              VARCHAR2(50),
    CREATED_DT              DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(50),
    UPDATED_DT              DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TRK_SHIPMENT PRIMARY KEY (COMPANY_CODE, PRIN_CODE, JOB_NO),
    CONSTRAINT FK_TRK_SHIPMENT_JOB FOREIGN KEY (COMPANY_CODE, PRIN_CODE, JOB_NO)
        REFERENCES WMSTST.TI_JOB (COMPANY_CODE, PRIN_CODE, JOB_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_TRK_STAGE CHECK (CURRENT_STAGE IN ('CUSTOMER', 'FFD_REVIEW', 'IN_PROGRESS', 'TRANSPORT', 'DC_TRANSPORT', 'COMPLETED')),
    CONSTRAINT CHK_TRK_TYPE CHECK (SHIPMENT_TYPE IN ('IMPORT', 'EXPORT', 'LAND_IMPORT', 'AIR_IMPORT')),
    CONSTRAINT CHK_TRK_DRY CHECK (IS_DRY IN ('Y', 'N')),
    CONSTRAINT CHK_TRK_IMP CHECK (IS_IMPORTANT IN ('Y', 'N'))
);

CREATE INDEX WMSTST.IDX_TRK_SHIPMENT_BL ON WMSTST.TRK_SHIPMENT(COMPANY_CODE, BL_NUMBER);
CREATE INDEX WMSTST.IDX_TRK_SHIPMENT_STAGE ON WMSTST.TRK_SHIPMENT(COMPANY_CODE, CURRENT_STAGE);

-- -----------------------------------------------------------------------------
-- 2. SHIPMENT OPERATIONAL TASKS
-- Dynamic task records linked to MS_APPROVER_LEVELS (FLOW_LEVEL 1 to 7)
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WMSTST.TRK_SHIPMENT_TASKS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE WMSTST.TRK_SHIPMENT_TASKS (
    TASK_ID                 VARCHAR2(36)  DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
    COMPANY_CODE            VARCHAR2(5)   NOT NULL,
    PRIN_CODE               VARCHAR2(5)   NOT NULL,
    JOB_NO                  VARCHAR2(15)  NOT NULL,
    FLOW_LEVEL              NUMBER(2)     NOT NULL, -- 1 to 7, matches MS_APPROVER_LEVELS
    TASK_TYPE               VARCHAR2(30)  NOT NULL, -- FFD_REVIEW, PERMIT, BAYAN, DO, CCRO, TRANSPORT, DC_OFFLOAD
    ASSIGNED_TEAM           VARCHAR2(50)  NOT NULL, -- Role desc from MS_APPROVER_LEVELS
    STATUS                  VARCHAR2(20)  DEFAULT 'IN_PROGRESS' NOT NULL, -- IN_PROGRESS, ON_HOLD, COMPLETED
    HOLD_ENTITY             VARCHAR2(30), -- SHIPPING_LINE, ROP, MOAF, PORT, OTHER
    HOLD_REASON             VARCHAR2(50), -- e.g. SL_DO_NOT_SENT, ROP_APPROVAL_PENDING, MOAF_APPROVAL_PENDING, etc.
    HOLD_REMARK             VARCHAR2(1000),
    RELEASE_REMARK          VARCHAR2(1000),
    DUE_AT                  DATE,
    ASSIGNED_TO             VARCHAR2(50),
    CREATED_BY              VARCHAR2(50),
    CREATED_DT              DATE          DEFAULT SYSDATE NOT NULL,
    COMPLETED_BY            VARCHAR2(50),
    COMPLETED_DT            DATE,
    CONSTRAINT PK_TRK_SHIPMENT_TASKS PRIMARY KEY (TASK_ID),
    CONSTRAINT FK_TRK_TASKS_SHIPMENT FOREIGN KEY (COMPANY_CODE, PRIN_CODE, JOB_NO)
        REFERENCES WMSTST.TRK_SHIPMENT (COMPANY_CODE, PRIN_CODE, JOB_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_TRK_TASK_STATUS CHECK (STATUS IN ('IN_PROGRESS', 'ON_HOLD', 'COMPLETED'))
);

CREATE INDEX WMSTST.IDX_TRK_TASKS_JOB ON WMSTST.TRK_SHIPMENT_TASKS(COMPANY_CODE, PRIN_CODE, JOB_NO, TASK_TYPE);
CREATE INDEX WMSTST.IDX_TRK_TASKS_STATUS ON WMSTST.TRK_SHIPMENT_TASKS(COMPANY_CODE, STATUS, DUE_AT);

-- -----------------------------------------------------------------------------
-- 3. CONTAINER-LEVEL TRACKING
-- Mirrors & extends TF_CONTAINER_DET with real-time operational execution stamps
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WMSTST.TRK_CONTAINERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE WMSTST.TRK_CONTAINERS (
    CONTAINER_ID            VARCHAR2(36)  DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
    COMPANY_CODE            VARCHAR2(5)   NOT NULL,
    PRIN_CODE               VARCHAR2(5)   NOT NULL,
    JOB_NO                  VARCHAR2(15)  NOT NULL,
    CONTAINER_NUMBER        VARCHAR2(50)  NOT NULL,
    SEAL_NO                 VARCHAR2(50),
    STATUS                  VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL, -- PENDING, ARRIVED, PULLED_OUT, OFFLOADED, RETURNED
    TRUCK_PLATE_NUMBER      VARCHAR2(50),
    DRIVER_NAME             VARCHAR2(100),
    EXPECTED_ARRIVAL_AT     DATE,
    ARRIVED_AT              DATE,
    ACTUAL_PULL_OUT_DATE    DATE,
    OFFLOADED_AT            DATE,
    OFFLOADED_BY            VARCHAR2(50),
    DC_REMARK               VARCHAR2(1000),
    TRANSPORT_REMARK        VARCHAR2(1000),
    CREATED_DT              DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_DT              DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TRK_CONTAINERS PRIMARY KEY (CONTAINER_ID),
    CONSTRAINT FK_TRK_CONTAINERS_SHIPMENT FOREIGN KEY (COMPANY_CODE, PRIN_CODE, JOB_NO)
        REFERENCES WMSTST.TRK_SHIPMENT (COMPANY_CODE, PRIN_CODE, JOB_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_TRK_CNTR_STATUS CHECK (STATUS IN ('PENDING', 'ARRIVED', 'PULLED_OUT', 'OFFLOADED', 'RETURNED'))
);

CREATE INDEX WMSTST.IDX_TRK_CNTR_NO ON WMSTST.TRK_CONTAINERS(COMPANY_CODE, CONTAINER_NUMBER);
CREATE INDEX WMSTST.IDX_TRK_CNTR_JOB ON WMSTST.TRK_CONTAINERS(COMPANY_CODE, PRIN_CODE, JOB_NO);

-- -----------------------------------------------------------------------------
-- 4. AUDIT & EVENT LOG
-- Records every stage movement, hold event, and task state change
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WMSTST.TRK_SHIPMENT_EVENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE WMSTST.TRK_SHIPMENT_EVENTS (
    EVENT_ID                VARCHAR2(36)  DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
    COMPANY_CODE            VARCHAR2(5)   NOT NULL,
    PRIN_CODE               VARCHAR2(5)   NOT NULL,
    JOB_NO                  VARCHAR2(15)  NOT NULL,
    EVENT_TYPE              VARCHAR2(50)  NOT NULL, -- STAGE_CHANGED, HOLD_APPLIED, HOLD_RELEASED, TASK_COMPLETED, CONTAINER_OFFLOADED, TRUCK_ASSIGNED
    STAGE_FROM              VARCHAR2(30),
    STAGE_TO                VARCHAR2(30),
    ACTOR_ID                VARCHAR2(50)  NOT NULL,
    REMARK                  VARCHAR2(2000),
    CREATED_DT              DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TRK_EVENTS PRIMARY KEY (EVENT_ID)
);

CREATE INDEX WMSTST.IDX_TRK_EVENTS_JOB ON WMSTST.TRK_SHIPMENT_EVENTS(COMPANY_CODE, PRIN_CODE, JOB_NO);

-- -----------------------------------------------------------------------------
-- 5. SEED DATA: MS_APPROVER_LEVELS FOR FREIGHT TRACKER
-- Example: Company 1001 (Broker: 4 Levels) vs Company 1002 (3PL Full: 7 Levels)
-- -----------------------------------------------------------------------------
MERGE INTO WMSTST.MS_APPROVER_LEVELS t
USING (
    -- 4-Level Broker Profile (Company 1001)
    SELECT '1001' AS COMPANY_CODE, 'FREIGHT_TRACKER' AS PROCESS, 'NORMAL_IMPORT' AS FLOW_CODE,
           'FFD_TEAM' AS LEVEL1_ROLE, 'PRO_TEAM' AS LEVEL2_ROLE, 'BAYAN_TEAM' AS LEVEL3_ROLE, 'SHIPPING_LINE' AS LEVEL4_ROLE,
           NULL AS LEVEL5_ROLE, NULL AS LEVEL6_ROLE, NULL AS LEVEL7_ROLE, 4 AS LAST_LEVEL FROM DUAL UNION ALL
    -- 7-Level Full 3PL Profile (Company 1002)
    SELECT '1002' AS COMPANY_CODE, 'FREIGHT_TRACKER' AS PROCESS, 'NORMAL_IMPORT' AS FLOW_CODE,
           'FFD_TEAM' AS LEVEL1_ROLE, 'PRO_TEAM' AS LEVEL2_ROLE, 'BAYAN_TEAM' AS LEVEL3_ROLE, 'SHIPPING_LINE' AS LEVEL4_ROLE,
           'ROP_TEAM' AS LEVEL5_ROLE, 'TRANSPORT_TEAM' AS LEVEL6_ROLE, 'DC_TEAM' AS LEVEL7_ROLE, 7 AS LAST_LEVEL FROM DUAL UNION ALL
    -- CFS Fast-Track Transfer Profile (Applies to all companies handling CFS)
    SELECT '1001' AS COMPANY_CODE, 'FREIGHT_TRACKER' AS PROCESS, 'CFS_TRANSFER' AS FLOW_CODE,
           'ROP_TEAM' AS LEVEL1_ROLE, NULL AS LEVEL2_ROLE, NULL AS LEVEL3_ROLE, NULL AS LEVEL4_ROLE,
           NULL AS LEVEL5_ROLE, NULL AS LEVEL6_ROLE, NULL AS LEVEL7_ROLE, 1 AS LAST_LEVEL FROM DUAL UNION ALL
    SELECT '1002' AS COMPANY_CODE, 'FREIGHT_TRACKER' AS PROCESS, 'CFS_TRANSFER' AS FLOW_CODE,
           'ROP_TEAM' AS LEVEL1_ROLE, NULL AS LEVEL2_ROLE, NULL AS LEVEL3_ROLE, NULL AS LEVEL4_ROLE,
           NULL AS LEVEL5_ROLE, NULL AS LEVEL6_ROLE, NULL AS LEVEL7_ROLE, 1 AS LAST_LEVEL FROM DUAL
) s
ON (t.COMPANY_CODE = s.COMPANY_CODE AND t.PROCESS = s.PROCESS AND t.FLOW_CODE = s.FLOW_CODE)
WHEN MATCHED THEN
    UPDATE SET t.LEVEL1_ROLE = s.LEVEL1_ROLE, t.LEVEL2_ROLE = s.LEVEL2_ROLE, t.LEVEL3_ROLE = s.LEVEL3_ROLE,
               t.LEVEL4_ROLE = s.LEVEL4_ROLE, t.LEVEL5_ROLE = s.LEVEL5_ROLE, t.LEVEL6_ROLE = s.LEVEL6_ROLE,
               t.LEVEL7_ROLE = s.LEVEL7_ROLE, t.LAST_LEVEL = s.LAST_LEVEL
WHEN NOT MATCHED THEN
    INSERT (COMPANY_CODE, PROCESS, FLOW_CODE, LEVEL1_ROLE, LEVEL2_ROLE, LEVEL3_ROLE, LEVEL4_ROLE, LEVEL5_ROLE, LEVEL6_ROLE, LEVEL7_ROLE, LAST_LEVEL)
    VALUES (s.COMPANY_CODE, s.PROCESS, s.FLOW_CODE, s.LEVEL1_ROLE, s.LEVEL2_ROLE, s.LEVEL3_ROLE, s.LEVEL4_ROLE, s.LEVEL5_ROLE, s.LEVEL6_ROLE, s.LEVEL7_ROLE, s.LAST_LEVEL);

-- -----------------------------------------------------------------------------
-- 6. SEED DATA: SEC_MODULE_DATA CATALOG FOR TRACKER TABS (SERIAL_NO 7001-7007)
-- -----------------------------------------------------------------------------
MERGE INTO WMSTST.SEC_MODULE_DATA t
USING (
    SELECT 7001 AS SERIAL_NO, 'FRT' AS APP_CODE, 'Shipment Tracker' AS LEVEL1, 'FFD Review' AS LEVEL2, NULL AS LEVEL3, 1 AS POSITION, '/freight/tracker/ffd' AS URL_PATH, 'FileText' AS ICON FROM DUAL UNION ALL
    SELECT 7002, 'FRT', 'Shipment Tracker', 'PRO Permits', NULL, 2, '/freight/tracker/permit', 'ShieldCheck' FROM DUAL UNION ALL
    SELECT 7003, 'FRT', 'Shipment Tracker', 'Customs Bayan', NULL, 3, '/freight/tracker/bayan', 'Landmark' FROM DUAL UNION ALL
    SELECT 7004, 'FRT', 'Shipment Tracker', 'Delivery Order', NULL, 4, '/freight/tracker/do', 'Ship' FROM DUAL UNION ALL
    SELECT 7005, 'FRT', 'Shipment Tracker', 'CCRO / Port Police', NULL, 5, '/freight/tracker/ccro', 'Lock' FROM DUAL UNION ALL
    SELECT 7006, 'FRT', 'Shipment Tracker', 'Transport Dispatch', NULL, 6, '/freight/tracker/transport', 'Truck' FROM DUAL UNION ALL
    SELECT 7007, 'FRT', 'Shipment Tracker', 'DC Offloading', NULL, 7, '/freight/tracker/dc', 'Warehouse' FROM DUAL
) s
ON (t.SERIAL_NO = s.SERIAL_NO)
WHEN NOT MATCHED THEN
    INSERT (SERIAL_NO, APP_CODE, LEVEL1, LEVEL2, LEVEL3, POSITION, URL_PATH, ICON, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT)
    VALUES (s.SERIAL_NO, s.APP_CODE, s.LEVEL1, s.LEVEL2, s.LEVEL3, s.POSITION, s.URL_PATH, s.ICON, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

COMMIT;
PROMPT '>>> 01_CREATE_FREIGHT_TRACKER_SCHEMA.sql completed successfully!';

