export const masterDefinitions = {
  rates: {
    table: "VMS_WAYBILL_RATES",
    text: ["city"],
    numbers: ["base_kms", "standard_revenue", "non_standard_revenue", "standard_kms_charge", "non_standard_kms_charge"],
  },
  wells: {
    table: "VMS_WAYBILL_WELLS",
    text: ["well_id", "city"],
    numbers: ["actual_kms"],
  },
  distances: {
    table: "VMS_WAYBILL_DISTANCES",
    text: ["well_id_1", "well_id_2"],
    numbers: ["distance"],
  },
} as const;

export type MasterKind = keyof typeof masterDefinitions;

export function validateMaster(kind: MasterKind, body: Record<string, unknown>) {
  const definition = masterDefinitions[kind];
  const values: Record<string, string | number> = {};
  for (const key of definition.text) {
    const input = body[key];
    if (typeof input !== "string" || !input.trim() || input.trim().length > 200) {
      throw new Error(`${key} is required and must be at most 200 characters.`);
    }
    values[key] = input.trim().replace(/\s+/g, " ").toUpperCase();
  }
  for (const key of definition.numbers) {
    const input = body[key];
    if ((typeof input !== "number" && typeof input !== "string") || String(input).trim() === "") {
      throw new Error(`${key} is required.`);
    }
    // Match Oracle NUMBER(14,3); reject silent rounding and negative charges.
    if (!/^\d{1,11}(\.\d{1,3})?$/.test(String(input).trim())) {
      throw new Error(`${key} must be a non-negative number with up to 3 decimal places and 11 whole digits.`);
    }
    values[key] = Number(input);
  }
  if (kind === "distances" && values.well_id_1 === values.well_id_2) {
    throw new Error("Select two different well IDs.");
  }
  return values;
}

const auditColumns = `
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  COMPANY_CODE VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(100),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(100),
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL`;

export const masterTableStatements = [
  `CREATE TABLE VMS_WAYBILL_RATES (
    ${auditColumns},
    CITY VARCHAR2(200) NOT NULL,
    BASE_KMS NUMBER(14,3) NOT NULL CHECK (BASE_KMS >= 0),
    STANDARD_REVENUE NUMBER(14,3) NOT NULL CHECK (STANDARD_REVENUE >= 0),
    NON_STANDARD_REVENUE NUMBER(14,3) NOT NULL CHECK (NON_STANDARD_REVENUE >= 0),
    STANDARD_KMS_CHARGE NUMBER(14,3) NOT NULL CHECK (STANDARD_KMS_CHARGE >= 0),
    NON_STANDARD_KMS_CHARGE NUMBER(14,3) NOT NULL CHECK (NON_STANDARD_KMS_CHARGE >= 0),
    CONSTRAINT VMS_WB_RATE_UQ UNIQUE (COMPANY_CODE, CITY)
  )`,
  `CREATE TABLE VMS_WAYBILL_WELLS (
    ${auditColumns},
    WELL_ID VARCHAR2(200) NOT NULL,
    CITY VARCHAR2(200) NOT NULL,
    ACTUAL_KMS NUMBER(14,3) NOT NULL CHECK (ACTUAL_KMS >= 0),
    CONSTRAINT VMS_WB_WELL_UQ UNIQUE (COMPANY_CODE, WELL_ID),
    CONSTRAINT VMS_WB_WELL_CITY_FK FOREIGN KEY (COMPANY_CODE, CITY)
      REFERENCES VMS_WAYBILL_RATES (COMPANY_CODE, CITY)
  )`,
  `CREATE TABLE VMS_WAYBILL_DISTANCES (
    ${auditColumns},
    WELL_ID_1 VARCHAR2(200) NOT NULL,
    WELL_ID_2 VARCHAR2(200) NOT NULL,
    DISTANCE NUMBER(14,3) NOT NULL CHECK (DISTANCE >= 0),
    CONSTRAINT VMS_WB_DIST_UQ UNIQUE (COMPANY_CODE, WELL_ID_1, WELL_ID_2),
    CONSTRAINT VMS_WB_DIST_DIFFERENT CHECK (WELL_ID_1 <> WELL_ID_2),
    CONSTRAINT VMS_WB_DIST_WELL1_FK FOREIGN KEY (COMPANY_CODE, WELL_ID_1)
      REFERENCES VMS_WAYBILL_WELLS (COMPANY_CODE, WELL_ID),
    CONSTRAINT VMS_WB_DIST_WELL2_FK FOREIGN KEY (COMPANY_CODE, WELL_ID_2)
      REFERENCES VMS_WAYBILL_WELLS (COMPANY_CODE, WELL_ID)
  )`,
];
