import { Response } from "express";
import { QueryExecutor } from "../../database/QueryExecutor";
import { RequestWithUser } from "../../interfaces/common.interface";
import { getCurrentTenantId } from "../../middleware/tenantContext.middleware";

const TABLE_NAME = "VMS_WAYBILL_REQUESTS";
const readyTenants = new Set<string>();

async function ensureTable(tenantId: string) {
  if (readyTenants.has(tenantId)) return;
  await QueryExecutor.executeRawQuery(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE ${TABLE_NAME} (
          ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          COMPANY_CODE VARCHAR2(50) NOT NULL,
          WAYBILL_LOAD_NUMBER VARCHAR2(200) NOT NULL,
          DESTINATION_NAME VARCHAR2(200) NOT NULL,
          SCHEDULED_VEHICLE VARCHAR2(200) NOT NULL,
          PICKUP_DATE VARCHAR2(50) NOT NULL,
          VENDOR_NAME VARCHAR2(200) NOT NULL,
          RIG_ID VARCHAR2(100) NOT NULL,
          FILE_NAME VARCHAR2(255),
          RAW_TEXT CLOB,
          STATUS VARCHAR2(30) DEFAULT ''PENDING'' NOT NULL,
          CREATED_BY VARCHAR2(100),
          CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;
  `);
  readyTenants.add(tenantId);
}

function value(input: unknown): string {
  return typeof input === "string" ? input.trim() : String(input ?? "").trim();
}

export async function listWaybillRequests(req: RequestWithUser, res: Response) {
  try {
    await ensureTable(getCurrentTenantId() || String(req.user?.tenantId || ""));
    const result = await QueryExecutor.executeRawQuery(
      `SELECT ID, WAYBILL_LOAD_NUMBER, DESTINATION_NAME, SCHEDULED_VEHICLE,
              PICKUP_DATE, VENDOR_NAME, RIG_ID, FILE_NAME, STATUS, CREATED_AT
         FROM ${TABLE_NAME}
        WHERE COMPANY_CODE = :company_code
        ORDER BY CREATED_AT DESC`,
      { company_code: value(req.user?.company_code) },
    );
    res.json({ success: true, data: result.rows || [] });
  } catch (error) {
    console.error("Unable to list waybill requests:", error);
    res.status(500).json({ success: false, message: "Unable to load waybill requests." });
  }
}

export async function createWaybillRequest(req: RequestWithUser, res: Response) {
  try {
    await ensureTable(getCurrentTenantId() || String(req.user?.tenantId || ""));
    const body = req.body as Record<string, unknown>;
    const fields = {
      company_code: value(req.user?.company_code || body.company_code),
      waybill_load_number: value(body.waybill_load_number),
      destination_name: value(body.destination_name),
      scheduled_vehicle: value(body.scheduled_vehicle),
      pickup_date: value(body.pickup_date),
      vendor_name: value(body.vendor_name),
      rig_id: value(body.rig_id),
      file_name: value(body.file_name) || null,
      raw_text: value(body.raw_text) || null,
      created_by: value(req.user?.loginid),
    };
    const missing = ["company_code", "waybill_load_number", "destination_name", "scheduled_vehicle", "pickup_date", "vendor_name", "rig_id"]
      .filter((key) => !fields[key as keyof typeof fields]);
    if (missing.length) {
      res.status(400).json({ success: false, message: `Missing waybill fields: ${missing.join(", ")}` });
      return;
    }
    await QueryExecutor.executeRawQuery(
      `INSERT INTO ${TABLE_NAME}
        (COMPANY_CODE, WAYBILL_LOAD_NUMBER, DESTINATION_NAME, SCHEDULED_VEHICLE,
         PICKUP_DATE, VENDOR_NAME, RIG_ID, FILE_NAME, RAW_TEXT, CREATED_BY)
       VALUES
        (:company_code, :waybill_load_number, :destination_name, :scheduled_vehicle,
         :pickup_date, :vendor_name, :rig_id, :file_name, :raw_text, :created_by)`,
      fields,
    );
    res.status(201).json({ success: true, message: "Waybill saved." });
  } catch (error) {
    console.error("Unable to save waybill request:", error);
    res.status(500).json({ success: false, message: "Unable to save waybill request." });
  }
}
