import { Response } from "express";
import oracledb, { Connection } from "oracledb";
import { TenantManager } from "../../database/TenantManager";
import { QueryExecutor } from "../../database/QueryExecutor";
import { RequestWithUser } from "../../interfaces/common.interface";
import { getCurrentTenantId } from "../../middleware/tenantContext.middleware";
import { ensureMasterTables } from "./waybillMasters.controller";
import { ensureWaybillTable } from "./waybill.controller";
import { amount, BillingSettings, calculateRevenue, DataRow, digest, emptyBillingSettings, RevenueRow, round3, validateBillingSettings } from "./waybillBilling.engine";

const schemaReady = new Map<string, Promise<void>>();
const ddl = [
  `CREATE TABLE VMS_WAYBILL_BILLING_CONFIG (
    COMPANY_CODE VARCHAR2(50) PRIMARY KEY, SETTINGS_JSON CLOB NOT NULL,
    UPDATED_BY VARCHAR2(100), UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
  )`,
  `CREATE TABLE VMS_WAYBILL_REVENUE (
    COMPANY_CODE VARCHAR2(50) NOT NULL, WAYBILL_ID NUMBER NOT NULL,
    LOAD_NUMBER VARCHAR2(200), DESTINATION_NAME VARCHAR2(200),
    SCHEDULED_VEHICLE VARCHAR2(200), PICKUP_DATE VARCHAR2(50), VENDOR_NAME VARCHAR2(200), RIG_ID VARCHAR2(100),
    BASE_REVENUE NUMBER(14,3), KMS_REVENUE NUMBER(14,3), TRIP_TYPE VARCHAR2(30), KMS_CHARGEABLE NUMBER(14,3),
    LOCAL_TRIP_REVENUE NUMBER(14,3), TOTAL_REVENUE NUMBER(14,3), STATUS VARCHAR2(30) NOT NULL,
    SOURCE_HASH VARCHAR2(64) NOT NULL, RESULT_JSON CLOB NOT NULL,
    UPDATED_BY VARCHAR2(100), UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT VMS_WB_REVENUE_PK PRIMARY KEY (COMPANY_CODE, WAYBILL_ID)
  )`,
  `CREATE TABLE VMS_WAYBILL_REVENUE_AUDIT (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    COMPANY_CODE VARCHAR2(50) NOT NULL, WAYBILL_ID NUMBER,
    ACTION VARCHAR2(30) NOT NULL, DETAILS_JSON CLOB NOT NULL,
    CREATED_BY VARCHAR2(100), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
  )`,
];

async function prepare(tenant: string, company: string) {
  let pending = schemaReady.get(tenant);
  if (!pending) {
    pending = (async () => {
      await ensureMasterTables(tenant);
      await ensureWaybillTable(tenant);
      for (const sql of ddl) await QueryExecutor.executeRawQuery(`BEGIN EXECUTE IMMEDIATE '${sql.replace(/'/g, "''")}';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`);
    })();
    schemaReady.set(tenant, pending);
  }
  try { await pending; } catch (error) { schemaReady.delete(tenant); throw error; }
  // This row is also the cross-process lock for company billing operations.
  await QueryExecutor.executeRawQuery(`BEGIN
    INSERT INTO VMS_WAYBILL_BILLING_CONFIG (COMPANY_CODE, SETTINGS_JSON) VALUES (:company, :settings);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;`, { company, settings: JSON.stringify(emptyBillingSettings) });
}

const lower = (rows: unknown[]) => rows.map((row) => Object.fromEntries(Object.entries(row as DataRow).map(([key, value]) => [key.toLowerCase(), value])));
async function query(conn: Connection, sql: string, binds: DataRow = {}, jsonColumn?: string) {
  const result = await conn.execute(sql, binds, {
    outFormat: oracledb.OUT_FORMAT_OBJECT,
    ...(jsonColumn ? { fetchInfo: { [jsonColumn]: { type: oracledb.STRING } } } : {}),
  });
  return lower(result.rows || []);
}

async function snapshot(conn: Connection, company: string) {
  const binds = { company };
  const waybills = await query(conn, `SELECT ID, WAYBILL_LOAD_NUMBER, DESTINATION_NAME, SCHEDULED_VEHICLE,
    PICKUP_DATE, VENDOR_NAME, RIG_ID FROM VMS_WAYBILL_REQUESTS WHERE COMPANY_CODE = :company ORDER BY ID`, binds);
  const wells = await query(conn, "SELECT WELL_ID, CITY, ACTUAL_KMS FROM VMS_WAYBILL_WELLS WHERE COMPANY_CODE = :company ORDER BY WELL_ID", binds);
  const rates = await query(conn, `SELECT CITY, BASE_KMS, STANDARD_REVENUE, NON_STANDARD_REVENUE,
    STANDARD_KMS_CHARGE, NON_STANDARD_KMS_CHARGE FROM VMS_WAYBILL_RATES WHERE COMPANY_CODE = :company ORDER BY CITY`, binds);
  const distances = await query(conn, "SELECT WELL_ID_1, WELL_ID_2, DISTANCE FROM VMS_WAYBILL_DISTANCES WHERE COMPANY_CODE = :company ORDER BY WELL_ID_1, WELL_ID_2", binds);
  const config = await query(conn, "SELECT SETTINGS_JSON FROM VMS_WAYBILL_BILLING_CONFIG WHERE COMPANY_CODE = :company", binds, "SETTINGS_JSON");
  const settings: BillingSettings = validateBillingSettings(JSON.parse(config[0].settings_json));
  return { rows: calculateRevenue(waybills, wells, rates, distances, settings), settings };
}

async function savedRows(conn: Connection, company: string): Promise<RevenueRow[]> {
  const result = await query(conn, "SELECT RESULT_JSON FROM VMS_WAYBILL_REVENUE WHERE COMPANY_CODE = :company ORDER BY WAYBILL_ID", { company }, "RESULT_JSON");
  return result.map((row) => JSON.parse(row.result_json));
}

async function persist(conn: Connection, company: string, actor: string, row: RevenueRow) {
  const fields = {
    load_number: row.waybill_load_number, destination_name: row.destination_name,
    scheduled_vehicle: row.scheduled_vehicle, pickup_date: row.pickup_date, vendor_name: row.vendor_name, rig_id: row.rig_id,
    base_revenue: row.base_revenue, kms_revenue: row.kms_revenue, trip_type: row.trip_type, kms_chargeable: row.kms_chargeable,
    local_trip_revenue: row.local_trip_revenue, total_revenue: row.total_revenue, status: row.status, source_hash: row.source_hash,
    result_json: { val: JSON.stringify(row), type: oracledb.CLOB }, updated_by: actor,
  };
  const keys = Object.keys(fields);
  await conn.execute(`MERGE INTO VMS_WAYBILL_REVENUE r
    USING (SELECT :company AS COMPANY_CODE, :id AS WAYBILL_ID FROM DUAL) s
    ON (r.COMPANY_CODE = s.COMPANY_CODE AND r.WAYBILL_ID = s.WAYBILL_ID)
    WHEN MATCHED THEN UPDATE SET ${keys.map((key) => `r.${key} = :${key}`).join(", ")}, r.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (COMPANY_CODE, WAYBILL_ID, ${keys.join(", ")})
      VALUES (:company, :id, ${keys.map((key) => `:${key}`).join(", ")})`,
  { ...fields, company, id: row.waybill_id });
}

async function audit(conn: Connection, company: string, actor: string, action: string, details: unknown, id: number | null = null) {
  await conn.execute(`INSERT INTO VMS_WAYBILL_REVENUE_AUDIT (COMPANY_CODE, WAYBILL_ID, ACTION, DETAILS_JSON, CREATED_BY)
    VALUES (:company, :id, :action, :details, :actor)`, { company, id, action, actor, details: { val: JSON.stringify(details), type: oracledb.CLOB } });
}

class RequestError extends Error {
  constructor(public status: number, message: string) { super(message); }
}

function handler(work: (conn: Connection, company: string, actor: string, req: RequestWithUser) => Promise<unknown>, write = false) {
  return async (req: RequestWithUser, res: Response) => {
    const tenant = getCurrentTenantId();
    const company = String(req.user?.company_code || "").trim();
    if (!tenant || !company) { res.status(403).json({ success: false, message: "Tenant and company are required." }); return; }
    let conn: Connection | undefined;
    try {
      await prepare(tenant, company);
      conn = await TenantManager.getConnection(tenant);
      // All reads for a calculation use one database snapshot. Changes during processing
      // are detected by source hashes on the next read/verification.
      await conn.execute(write ? "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE" : "SET TRANSACTION READ ONLY");
      if (write) await conn.execute("SELECT COMPANY_CODE FROM VMS_WAYBILL_BILLING_CONFIG WHERE COMPANY_CODE = :company FOR UPDATE", { company });
      const data = await work(conn, company, String(req.user?.loginid || ""), req);
      await conn.commit();
      res.json({ success: true, data });
    } catch (error) {
      if (conn) await conn.rollback();
      const conflict = (error as { errorNum?: number }).errorNum === 8177;
      const status = error instanceof RequestError ? error.status : conflict ? 409 : 500;
      if (status === 500) console.error("Waybill billing failed:", error);
      res.status(status).json({ success: false, message: error instanceof RequestError ? error.message : conflict ? "Billing data changed during processing. Please retry." : "Unable to process waybill billing." });
    } finally { if (conn) await conn.close(); }
  };
}

export const getWaybillBilling = handler(async (conn, company) => {
  const current = await snapshot(conn, company);
  const saved = new Map((await savedRows(conn, company)).map((row) => [row.waybill_id, row]));
  return {
    settings: current.settings,
    rows: current.rows.map((row) => {
      const previous = saved.get(row.waybill_id);
      return previous?.source_hash === row.source_hash
        ? { ...previous, processed: true, stale: false, review_token: digest(previous) }
        : { ...row, processed: false, stale: Boolean(previous) };
    }),
  };
});

export const saveWaybillBillingSettings = handler(async (conn, company, actor, req) => {
  let settings: BillingSettings;
  try { settings = validateBillingSettings(req.body || {}); }
  catch (error) { throw new RequestError(400, (error as Error).message); }
  const old = await query(conn, "SELECT SETTINGS_JSON FROM VMS_WAYBILL_BILLING_CONFIG WHERE COMPANY_CODE = :company", { company }, "SETTINGS_JSON");
  await conn.execute(`UPDATE VMS_WAYBILL_BILLING_CONFIG SET SETTINGS_JSON = :settings, UPDATED_BY = :actor,
    UPDATED_AT = SYSTIMESTAMP WHERE COMPANY_CODE = :company`, { company, actor, settings: JSON.stringify(settings) });
  await audit(conn, company, actor, "SETTINGS", { before: JSON.parse(old[0].settings_json), after: settings });
  return settings;
}, true);

export const processWaybillBilling = handler(async (conn, company, actor) => {
  const current = await snapshot(conn, company);
  const saved = new Map((await savedRows(conn, company)).map((row) => [row.waybill_id, row]));
  let updated = 0;
  for (const row of current.rows) {
    const previous = saved.get(row.waybill_id);
    if (previous?.source_hash === row.source_hash) continue; // Preserve verified/manual rows until their inputs change.
    await persist(conn, company, actor, row);
    await audit(conn, company, actor, "PROCESS", { before: previous || null, after: row }, row.waybill_id);
    updated++;
  }
  return { count: current.rows.length, updated };
}, true);

export const reviewWaybillRevenue = handler(async (conn, company, actor, req) => {
  const id = Number(req.params.id);
  if (!Number.isSafeInteger(id) || id <= 0) throw new RequestError(400, "Invalid waybill ID.");
  const current = await snapshot(conn, company);
  const live = current.rows.find((row) => row.waybill_id === id);
  if (!live) throw new RequestError(404, "Waybill not found.");
  const saved = (await savedRows(conn, company)).find((row) => row.waybill_id === id);
  if (!saved || saved.source_hash !== live.source_hash || req.body?.source_hash !== live.source_hash) {
    throw new RequestError(409, "Waybill, master data or billing settings changed. Process and reload revenue before reviewing.");
  }
  if (req.body?.review_token !== digest(saved)) throw new RequestError(409, "Another review changed this row. Reload before saving your review.");
  const row = { ...live };
  const note = String(req.body?.review_note || "").trim();
  if (note.length > 2000) throw new RequestError(400, "Review note must be at most 2000 characters.");
  if (req.body?.mode === "manual") {
    if (!note) throw new RequestError(400, "A reason is required for team-entered revenue.");
    try {
      row.base_revenue = amount(req.body.base_revenue);
      row.kms_chargeable = amount(req.body.kms_chargeable);
      row.kms_revenue = amount(req.body.kms_revenue);
      row.local_trip_revenue = amount(req.body.local_trip_revenue);
      row.total_revenue = amount(round3(row.base_revenue + row.kms_revenue + row.local_trip_revenue));
    } catch (error) { throw new RequestError(400, (error as Error).message); }
    row.status = "MANUAL_VERIFIED";
    row.calculation = [...live.calculation, "Team-entered amounts override automatic calculations; see review reason."];
  } else if (req.body?.mode === "verify") {
    if (live.status !== "READY") throw new RequestError(400, "Resolve the listed issues or enter team-reviewed amounts.");
    row.status = "VERIFIED";
  } else throw new RequestError(400, "Choose verify or manual review.");
  row.reviewed_by = actor; row.reviewed_at = new Date().toISOString(); row.review_note = note;
  await persist(conn, company, actor, row);
  await audit(conn, company, actor, "REVIEW", { before: saved, after: row }, id);
  return row;
}, true);
